__TESTS__/unit/namespaces/Actions.test.ts, __TESTS__/unit/namespaces/Index.test.ts, __TESTS__/unit/transformation/TransformableImage.test.ts, __TESTS__/unit/url/createCloudinaryURL.test.ts
Notes:
This PR is intended to reach the required test coverage so that Travis CI can start passing successfully.
Some of these tests will not be required in the future, while others will obviously change
=> Add required tests to reach test coverage

__TESTS__/unit/actions/Overlay.test.ts, __TESTS__/unit/transformation/TransformableImage.test.ts, src/actions/layers/ILayerAction.ts, src/actions/layers/Layers.ts, src/actions/layers/Sources.ts, src/transformation/TransformableImage.ts, src/transformation/Transformation.ts
Notes.
1. This PR includes a fix for joining actions with '/' 
2. Note the difference between PHP and this PR, for size reasons we can't use the same approach.
3. This is not aligned to the code generator, which will require changes.
4. this is not the complete overlay implementation, but merely a POC to decide if this is how we want to proceed
=> Add overlay action

__TESTS__/unit/actions/Variable.test.ts, scripts/updateCompliationTests.js, src/actions/variable/Variable.ts
- Refactored the structure and fixed exports of Variable, so it matches other Actions.
- Skipped tests are to be implemented in the future
=> Refactor Variable to VariableAction and added skipped tests

__TESTS__/unit/actions/Resize.test.ts, __TESTS__/unit/types/Gravity.test.ts, scripts/createEntrypoints.ts, src/actions/resize/IResizeAction.ts, src/actions/resize/ResizeAction.ts, src/actions/resize/aspectRatio.ts, src/actions/resize/crop.ts, src/actions/resize/fill.ts, src/actions/resize/minimumPad.ts, src/constants/gravityObjects/GravityObjects.ts, src/index.ts, src/parameters/ParamValue.ts, src/params/gravity/Gravity.ts
Notes for the reviewer:
- I could not find a proper place to put AutoGravity, It has no definite place since it's a very unique Entity. Suggestions are welcomed.
- AutoGravity is not tree-shakable, you'll get all the static functions once you import it. It's very small but still worth noting. The alternative looked very confusing (in terms of imports)
- There are still some issues with the compilation tests, so not all of Gravity could be implemented, however the vast majority is included in this PR.
=> Add Gravity param to Base

__TESTS__/unit/actions/Overlay.test.ts, __TESTS__/unit/types/Position.test.ts, scripts/createEntrypoints.ts, src/actions/Action.ts, src/actions/layers/Layers.ts, src/params/gravity/Gravity.ts, src/params/position/Position.ts
Implemented Position as a Param for Overlay.
=> Implement Position param

__TESTS__/TestUtils/expectESMToMatchDefault.ts, __TESTS__/unit/actions/Overlay.test.ts, __TESTS__/unit/types/BlendMode.test.ts, src/actions/layers/Layers.ts, src/params/blendMode/BlendMode.ts
- Added a Utility to match ESM to default packages (expectESMToMatchDefault)
- Added implementation needed for BlendMode
- Refactored some tests to reduce bloat in the amount of lines
=> Implement blendmode for overlays

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/Effect.ts, src/actions/effect/colorize.ts, src/actions/effect/oilPaint.ts, src/actions/effect/shadow.ts
added effect colorize, oilpaint, shadow
=> added effect colorize, oilpaint, shadow

src/interfaces/Config/IAuthTokenConfig.ts, src/interfaces/Config/ICloudConfig.ts
=> Add docstrings to Configuration

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/Effect.ts, src/actions/effect/outline.ts, src/constants/outline/Outline.ts, src/index.ts
=> Added effect.outline

src/actions/delivery/dpr.ts
=> fixed dpr docstring

__TESTS__/TestUtils/expectESMToMatchDefault.ts, __TESTS__/unit/actions/Effect.test.ts, __TESTS__/unit/actions/Quality.test.ts, src/actions/Action.ts, src/actions/effect/EffectAction.ts, src/actions/roundCorners/RoundCornersAction.ts, src/config/CloudConfig.ts, src/instance/Cloudinary.ts, src/parameters/Param.ts, src/parameters/ParamValue.ts, src/params/formats/Formats.ts, src/transformation/Transformation.ts, src/url/urlUtils/isFileName.ts, src/url/urlUtils/isUrl.ts, src/url/urlUtils/publicIDContainsVersion.ts, src/utils/dataStructureUtils.ts, src/utils/prepareColor.ts
This PR fixes lint errors
* Remove unused variables (Or use them)
* Add return types
=> Fix lint warnings

__TESTS__/unit/actions/Adjust.test.ts, __TESTS__/unit/actions/Resize.test.ts, src/actions/adjust/Adjust.ts, src/actions/resize/ResizeAction.ts, src/constants/colors/Colors.ts
Add X,Y,Z to Resize, fix two small unrelated typos
=> Add missing x,y,z to resize, also fix two typos

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, src/utils/dataStructureUtils.ts
=> fixed broken build

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/Effect.ts, src/actions/effect/styleTransfer.ts, src/actions/layers/Layers.ts, src/params/sources/ISource.ts
- Create StyleTransfer action
- Extend Layer to support StyleTransfer
- Fix a few type errors in Layer
Implementation is more 'JS friendly', however compilation tests work 'as-is'
=> Add Effect Style Transfer

__TESTS__/unit/actions/Resize.test.ts, src/actions/resize/ResizeAction.ts, src/params/resizeMode/ResizeMode.ts
Implement resizeMode for resizeAction
=> Add resizeMode

__TESTS__/unit/actions/Underlay.test.ts, src/actions/effect/styleTransfer.ts, src/actions/layers/ILayerAction.ts, src/actions/layers/Layers.ts, src/transformation/Transformation.ts
Added support for underlay in Layer
Removed use of ILayer
=> Add underlay support

__TESTS__/unit/actions/CustomFunction.test.ts, src/actions/Action.ts, src/actions/Actions.ts, src/actions/border/solid.ts, src/actions/customFunction/CustomFunction.ts, src/actions/customFunction/CustomFunctionAction.ts, src/actions/effect/outline.ts, src/transformation/Transformation.ts, src/utils/base64Encode.ts
This PR adds CustomFunction support.
- We're currently missing support for a URL-safe base64 function, but a separate issue is currently open for that, it was added as a skipped test for future reference.
- There's a piece of isomorphic code that's tricky to test under Jest, browser-specific implementation is not currently tested, this will need to be improved upon in the future.
=> Implement customFunction action

__TESTS__/unit/utils/toFloatAsString.test.ts, src/actions/delivery/dpr.ts, src/actions/resize/ResizeAction.ts, src/utils/toFloatAsString.ts
This PR refactors out the toFloatAsString function and greatly improves it (The original implementation was extremely naive)
- N/A Implementation is aligned with PHP Reference(If different, please specify why)
=> Refactor out and enhance toFloatAsString

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/artisticFilter.ts
Fix artistic filter transformation
=> Fix artistic filter transformation

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, __TESTS__/unit/actions/Adjust.test.ts, src/actions/adjust/Adjust.ts
Added missing functionality to adjust.
Added missing JSdoc
There are still things that are missing from the spec such as improve and viesusCorrect.
=> Update action adjust

src/actions/condition/Condition.ts, src/transformation/Transformation.ts
=> updated conditionals jsdocs

__TESTS__/unit/actions/CustomFunction.test.ts, src/actions/customFunction/CustomFunctionAction.ts
Fix remote function safe base64 url
=> Fix remote function safe base64 url

__TESTS__/unit/actions/Delivery.test.ts, src/actions/delivery/Delivery.ts, src/actions/delivery/defaultImage.ts
=> Added Delivery.defaultimage

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/cartoonify.ts
=> Align cartoonify

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/Effect.ts, src/actions/effect/blurRegion.ts
=> Align blur-region

__TESTS__/unit/actions/Resize/LimitPadAction.test.ts, src/actions/resize/ResizeActions/LimitPadAction.ts
=> Align limit pad

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/Effect.ts, src/actions/effect/gradientFade.ts, src/constants/gradientFade/GradientFade.ts
=> Add gradient fade

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, __TESTS__/unit/actions/Effect.test.ts, src/actions/effect/Effect.ts, src/actions/effect/assistColorBlind.ts
=> Add assist_colorblind

__TESTS__/unit/actions/Resize/ThumbAction.test.ts, src/actions/effect/assistColorBlind.ts, src/actions/resize/ResizeActions/ThumbAction.ts
=> Fix failing build

DOCS.README.md, package.json
This PR Changes the home page of the docs website, providing different content than the github repository
=> Change the home page of the docs

src/actions/Action.ts, src/actions/adjust/leveled/autoColor.ts, src/actions/adjust/leveled/blue.ts, src/actions/adjust/leveled/brightness.ts, src/actions/adjust/leveled/contrast.ts, src/actions/adjust/leveled/green.ts, src/actions/adjust/leveled/red.ts, src/actions/adjust/leveled/saturation.ts, src/actions/effect/EffectActions/EffectActionWithLevel.ts, src/actions/effect/EffectActions/LeveledEffectAction.ts
=> Align jsdoc for adjust/leveled action

src/actions/adjust/Adjust.ts, src/actions/adjust/ImproveAction.ts
=> fix jsdocs

src/actions/resize/ResizeActions/FillPadAction.ts, src/actions/resize/ResizeActions/ImaggaCropAction.ts, src/actions/resize/ResizeActions/ImaggaScaleAction.ts, src/actions/resize/ResizeActions/LimitPadAction.ts, src/actions/resize/ResizeActions/ResizeAdvancedAction.ts, src/actions/resize/ResizeActions/ResizeSimpleAction.ts, src/actions/resize/ResizeActions/ScaleAction.ts, src/actions/resize/ResizeActions/ThumbAction.ts
After a discussion with @nitzanj, it became obvious that all resize actions have aspectRatio.
This PR  moves it to the BaseResize action
=> More aspect ratio to base resize

src/actions/adjust/By3dLut.ts
Adds a missing docstring for an internal class
=> Add missing docs for an internal class

src/actions/background/Background.ts, src/actions/background/BackgroundAction.ts, src/actions/background/BlurredBackgroundAction.ts, src/actions/background/border.ts, src/actions/background/color.ts
=> updated background jsdocs

src/actions/variable/SetAction.ts, src/actions/variable/SetFromContextAction.ts, src/actions/variable/SetFromMetadataAction.ts, src/actions/variable/SetReferenceAction.ts, src/actions/variable/Variable.ts, src/actions/variable/VariableAction.ts
aligned variable jsdocs
Please see all double @
=> aligned variable jsdoc

src/actions/transcode/AudioCodecAction.ts, src/actions/transcode/AudioFrequencyAction.ts, src/actions/transcode/BitRateAction.ts, src/actions/transcode/FPSAction.ts, src/actions/transcode/FPSRangeAction.ts, src/actions/transcode/KeyframeIntervalsAction.ts, src/actions/transcode/StreamingProfile.ts, src/actions/transcode/ToAnimatedAction.ts, src/actions/transcode/Transcode.ts
=> Align Transcode jsdocs

src/actions/adjust/RecolorAction.ts
=> Align re-color

__TESTS__/unit/actions/Adjust.test.ts, src/actions/adjust/ImproveAction.ts, src/values/improveMode/ImproveMode.ts
=> Align JSDocs of Improve

DOCS.README.md, src/interfaces/Config/ICloudinaryAssetConfigurations.ts, src/interfaces/Config/ICloudinaryConfigurations.ts, src/interfaces/Config/IURLConfig.ts
- Add JSdoc to various config interfaces
- Fix typos in landing page
=> Fix typeos and formatting in landing page

src/actions/Action.ts, src/transformation/Transformation.ts
=> Align JSDocs for AddFlag

src/actions/rotate/RotateAction.ts, src/actions/rotate/byAngle.ts, src/actions/rotate/mode.ts, src/values/rotate/Rotate.ts
... A few words
Aligned rotate jsdocs
=> aligned rotate jsdocs

src/actions/adjust/simple/viesusCorrect.ts
Add missing docstrings for a class
=> Add missing class documentation

__TESTS__/unit/actions/Adjust.test.ts, src/actions/adjust/simple/viesusCorrect.ts
Fix a small bug in the viesus correction string
=> Fix a bug in viesus_correct string

src/actions/roundCorners/RoundCorners.ts, src/actions/roundCorners/RoundCornersAction.ts, src/actions/roundCorners/byRadius.ts, src/actions/roundCorners/max.ts
=> aligned roundCorners jsdocs

__TESTS__/unit/actions/Quality.test.ts, src/actions/delivery/quality.ts, src/values/chromaSubSampling/ChromaSubSampling.ts
Align docs for Quality
Align spec Quailty
=> Add subSampling and align docs

__TESTS__/unit/actions/Resize/ScaleAction.test.ts, src/actions/resize/ResizeActions/ScaleAction.ts
Rename isLiquid to liquidRescaling
=> Rename isLiquid to liquidRescaling

src/values/background/shared/auto/BackgroundAutoBorderQualifier.ts, src/values/background/shared/auto/BackgroundAutoPredominantQualifier.ts, src/values/background/shared/base/BaseCommonBackground.ts, src/values/background/shared/base/BaseGradientBackground.ts, src/values/background/shared/gradient/BackgroundBorderGradientQualifier.ts, src/values/background/shared/gradient/BackgroundPredominantGradientQualifier.ts
=> Add missing jsdocs

src/actions/Action.ts, src/actions/delivery/DeliveryAction.ts, src/actions/namedTransformation/INamedTransformationAction.ts, src/actions/namedTransformation/NamedTransformation.ts, src/actions/namedTransformation/NamedTransformationAction.ts, src/actions/rotate/RotateAction.ts, src/actions/roundCorners/byRadius.ts, src/actions/roundCorners/max.ts, src/actions/videoEdit/TrimAction.ts, src/interfaces/IAction.ts, src/transformation/Transformation.ts
Remove IAction, and refactor needed code for this removal
IAction was a residue from the initial development that never had a purpose, this PR removes it from the codebase.
=> Remove IAction, and refactor needed code for this removal

__TESTS__/unit/actions/Resize/AspectRatio.test.ts, src/actions/resize/ResizeActions/shared/ResizeSimpleAction.ts, src/utils/toFloatAsString.ts, src/values/aspectRatio/AspectRatio.ts
updated aspect ratio with common methods
=> updated aspect ratio

__TESTS__/unit/actions/Cutter.test.ts, src/actions/cutter/Cutter.ts, src/actions/cutter/CutterAction.ts, src/actions/cutter/source.ts
Aligned cutter action along with jsdocs
=> updated cutter action

__TESTS__/unit/actions/Variable.test.ts, src/actions/variable/SetAction.ts, src/actions/variable/Variable.ts, src/actions/variable/VariableAction.ts, src/qualifier/QualifierValue.ts, src/utils/dataStructureUtils.ts, src/values/expression/Expression.ts
=> Aligned expression with spec

DOCS.README.md, __TESTS__/unit/actions/Delivery.test.ts, __TESTS__/unit/actions/Effect.test.ts, __TESTS__/unit/actions/Quality.test.ts, __TESTS__/unit/actions/Rotate.test.ts, src/actions/effect/assistColorBlind.ts, src/actions/effect/cartoonify.ts, src/actions/effect/gradientFade.ts, src/actions/effect/outline.ts, src/actions/effect/shadow.ts, src/actions/effect/simulateColorBlind.ts, src/actions/effect/styleTransfer.ts, src/actions/effect/vectorize.ts, src/actions/overlay/LayerAction.ts, src/actions/rotate/RotateAction.ts, src/actions/videoEdit/VideoEdit.ts, src/actions/videoEdit/VolumeAction.ts, src/transformation/Transformation.ts, src/values/formats/Formats.ts, src/values/gradientFade/GradientFade.ts, src/values/quality/Quality.ts, src/values/rotate/Rotate.ts
- Remove unneeded imports (Volume)
- Add various return statements that were missing
- Improve types for Effect
- Change Quality from Enum to functions
- Change RotationMode from Enum to functions
- Change GradientFade from Enum to functions
- All changes have their JSdocs added to them
- [X ]Tests - Add proper tests to the added code
=> Align codebase to latest compilation tests

DOCS.README.md, README.md
This PR provides a more comprehensive 'getting started' tutorial for the front page of the JSDoc website
This PR also links from the readme page to the documentation, instead of maintaining a duplication
The syntax shown here (Cloudinary instance) will be available once this PR is approved
https://github.com/cloudinary/cloudinary-js-base/pull/196
=> Update the documentation README and DOCS.README

src/actions/effect/blurRegion.ts, src/actions/effect/pixelateRegion.ts, src/actions/resize/ResizeActions/shared/ResizeAdvancedActionWithPosition.ts
- Add string types to functions that accept expressions
=> Add string types to functions that accept expressions

src/actions/Action.ts, src/config/BaseConfig.ts, src/interfaces/Config/IAccountConfig.ts, src/qualifier/Qualifier.ts, src/qualifier/QualifierValue.ts, src/utils/dataStructureUtils.ts
Replace unknown types with any
=> Replace unknowns with any

__TESTS__/unit/Action/Action.test.ts, __TESTS__/unit/Instance/Cloudinary.test.ts, __TESTS__/unit/actions/Adjust.test.ts, __TESTS__/unit/actions/Background.test.ts, __TESTS__/unit/actions/Border.test.ts, __TESTS__/unit/actions/Condition.test.ts, __TESTS__/unit/actions/Delivery.test.ts, __TESTS__/unit/actions/Effect.test.ts, __TESTS__/unit/actions/Flag.test.ts, __TESTS__/unit/actions/NamedTransformation.test.ts, __TESTS__/unit/actions/Overlay.test.ts, __TESTS__/unit/actions/PSDTools.test.ts, __TESTS__/unit/actions/Quality.test.ts, __TESTS__/unit/actions/Transcode.test.ts, __TESTS__/unit/actions/Underlay.test.ts, __TESTS__/unit/actions/Variable.test.ts, __TESTS__/unit/actions/VideoEdit.test.ts, __TESTS__/unit/config/cloudinaryConfig.test.ts, __TESTS__/unit/transformation/Transformation.test.ts, __TESTS__/unit/url/createCloudinaryURL.test.ts, __TESTS__/unit/urlConfig.test.ts, src/config/URLConfig.ts, src/url/cloudinaryURL.ts
This PR sets secure as a default boolean value (true)
=> Set secure as a default for url configuration

src/transformation/Transformation.ts
This PR prevents empty actions from creeping into the URL for cases where an action returns an empty string.
=> Add filter to prevent empty actions

package.json
Change the license field in package.json
=> Change license field

src/index.ts
Add export to transformableVideo
=> Add TransformableVideo to the root exports

__TESTS__/unit/actions/Variable.test.ts, src/actions/variable/VariableAction.ts
Align Variable (change to asFloat and asInteger)
=> Align variable.set (asFloat, asInteger)

src/actions/delivery/Delivery.ts, src/transformation/Transformation.ts, src/values/quality/Quality.ts
- Add class Delivery for better auto import
- Change namespace from 'QualityValues' to Quality (
=> Align Quality

__TESTS__/unit/actions/Rotate.test.ts, src/actions/rotate/RotateAction.ts, src/actions/rotate/mode.ts, src/values/rotate/Rotate.ts
- Align rotation mode
- provide better IDE type safety for rotate
=> Align rotation mode, and provide better IDE type safety

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/colorize.ts
The level value for colorize is now optional
=> Align colorize

src/actions/transcode/ToAnimatedAction.ts, src/actions/transcode/Transcode.ts, src/values/animatedFormat/AnimatedFormat.ts
Improve Transcode's types, import and export statements
=> Align transcode

__TESTS__/unit/actions/Delivery.test.ts, __TESTS__/unit/actions/Transcode.test.ts, __TESTS__/unit/values/format/Foramt.test.ts, src/values/format/Format.ts
Add all the missing formats, and missing tests
=> Add all the missing formats, and tests

__TESTS__/unit/actions/Background.test.ts, src/values/background/shared/base/BaseGradientBackground.ts, src/values/gradientDirection/GradientDirection.ts
Align GradientDirection and improve exports
=> Align GradientDirection and improve exports

src/qualifier/QualifierValue.ts, src/values/gravity/Gravity.ts, src/values/gravity/GravityQualifier.ts, src/values/gravity/OCR/OCR.ts, src/values/gravity/autoGravity/AutoGravity.ts, src/values/gravity/compassGravity/CompassGravity.ts, src/values/gravity/focusOnGravity/FocusOnGravity.ts, src/values/gravity/qualifiers/autoFocus/AutoFocus.ts, src/values/gravity/qualifiers/compass/Compass.ts, src/values/gravity/qualifiers/compass/CompassQualifier.ts, src/values/gravity/qualifiers/focusOn/FocusOn.ts, src/values/gravity/qualifiers/focusOn/FocusOnValue.ts
Align exports for Gravity and fix JSDocs
=> Align exports for Gravity

src/values/background/Background.ts, src/values/background/shared/BlurredBackgroundAction.ts, src/values/background/shared/auto/BackgroundAutoBorderQualifier.ts, src/values/background/shared/auto/BackgroundAutoPredominantQualifier.ts, src/values/background/shared/base/BackgroundQualifier.ts, src/values/background/shared/base/BaseCommonBackground.ts, src/values/background/shared/base/BaseGradientBackground.ts, src/values/background/shared/gradient/BackgroundBorderGradientQualifier.ts, src/values/background/shared/gradient/BackgroundPredominantGradientQualifier.ts
=> Align exports and fix JSDocs

src/values/chromaSubSampling/ChromaSubSampling.ts
Align exports for Chroma sub sampling
=> Align exports

src/values/dither/Dither.ts
=> Align exports for dither

src/actions/Actions.ts, src/actions/condition/Condition.ts, src/actions/variable/SetAction.ts, src/actions/variable/SetFromContextAction.ts, src/actions/variable/Variable.ts, src/actions/variable/VariableAction.ts, src/qualifier/QualifierValue.ts, src/values/expression/Expression.ts, src/values/expression/ExpressionQualifier.ts
- Align export expression/Variable
- Remove export variable from Actions.ts to prevent the IDE from offering two different places to input Variable
=> Align export expression/Variable

.release-it.json
Fix a problem in the release process where the root package json wouldn't get added to git
=> Fix a bug in the release process

__TESTS__/unit/types/BlendMode.test.ts, src/values/blendMode.ts
=> Align blendmode

__TESTS__/unit/Action/Action.test.ts, src/internal/Action.ts
Add the ability to eset and get action tags
=> Add the ability to eset and get action tags

__TESTS__/TestUtils/createCloudinaryImage.ts, __TESTS__/TestUtils/createCloudinaryVideo.ts, __TESTS__/TestUtils/transformations/sampleEmptyTextStyle.ts, __TESTS__/TestUtils/transformations/sampleTextStyle.ts, __TESTS__/TestUtils/transformations/sampleTxResizePad.ts, src/actions/adjust/simple/ViesusCorrectAdjustAction.ts, src/actions/effect/blur/blur.ts, src/actions/effect/colorize.ts, src/actions/effect/dither.ts, src/actions/effect/leveled/makeTransparent.ts, src/actions/effect/pixelate/pixelate.ts, src/actions/rotate/RotateAction.ts, src/actions/rotate/mode.ts, src/config/BaseConfig.ts, src/config/interfaces/Config/IAccountConfig.ts, src/internal/qualifier/QualifierValue.ts, src/internal/utils/dataStructureUtils.ts, src/values/background/shared/BlurredBackgroundAction.ts, src/values/background/shared/auto/BackgroundAutoBorderQualifier.ts, src/values/background/shared/auto/BackgroundAutoPredominantQualifier.ts, src/values/background/shared/base/BackgroundQualifier.ts, src/values/background/shared/base/BaseCommonBackground.ts, src/values/background/shared/base/BaseGradientBackground.ts, src/values/background/shared/gradient/BackgroundBorderGradientQualifier.ts, src/values/background/shared/gradient/BackgroundPredominantGradientQualifier.ts, src/values/rotate/RotationModeQualifierValue.ts, src/values/source/sourceTypes/TextSource.ts
Fix various ESLint issues and DocStrings
=> Fix various ESLint issues and DocStrings

__TESTS__/unit/actions/Effect.test.ts, __TESTS__/unit/actions/PSDTools.test.ts, __TESTS__/unit/values/valueImports.test.ts, src/actions.ts, src/actions/effect.ts, src/actions/psdTools.ts, src/values.ts, src/values/dither.ts, src/values/outlineMode.ts, src/values/simulateColorBlind.ts
Various alignments to the Spec/Code Generator
=> Align to code generator

__TESTS__/unit/actions/Reshape.test.ts, jest.config.json, src/actions/effect/styleTransfer.ts, src/actions/reshape/CutByImage.ts, src/values/source/sourceTypes/TextSource.ts
Fix cut by image, remove redundant code, and increase test coverage
=> Fix cut by image, remove redundant code and increase test coverage

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/assistColorBlind.ts
Align assist colorblind to the spec
=> Align assist color blind to the spec

__TESTS__/unit/actions/Variable.test.ts, src/actions/variable.ts, src/actions/variable/SetAction.ts, src/actions/variable/SetAssetReferenceAction.ts, src/actions/variable/SetFromContextAction.ts, src/actions/variable/SetFromMetadataAction.ts, src/actions/variable/VariableAction.ts
Align variable names and JSDoc
=> Align variable names and JSDoc

__TESTS__/unit/actions/Reshape.test.ts, src/actions/effect/styleTransfer.ts, src/actions/reshape.ts, src/actions/reshape/CutByImage.ts, src/actions/reshape/Distort.ts, src/actions/reshape/DistortArc.ts, src/actions/reshape/Shear.ts
Align all of `reshape` to the specification
=> Add missing reshape actions

__TESTS__/unit/actions/PSDTools.test.ts, src/actions/psdTools.ts, src/actions/psdTools/ClipAction.ts, src/actions/psdTools/GetLayerAction.ts, src/actions/psdTools/SmartObjectAction.ts
=> Align PSDtools.clip and fix various JSDoc issues

__TESTS__/unit/actions/Overlay.test.ts, src/values/source/BaseSource.ts, src/values/source/sourceTypes/ImageSource.ts, src/values/source/sourceTypes/SubtitlesSource.ts, src/values/source/sourceTypes/TextSource.ts, src/values/source/sourceTypes/VideoSource.ts
=> Fix encoding of overlays

__TESTS__/unit/actions/Variable.test.ts, src/actions/variable.ts
- Fix an issue with variable export
- Add tests
- Refactor tests
=> Fix an issue with variable export, add tests and refactor tests

src/values/animatedFormat.ts
=> Align animated format

__TESTS__/unit/actions/Transcode.test.ts, __TESTS__/unit/values/valueImports.test.ts, src/values/streamingProfile.ts
Align streaming profile to camelCase
=> Align streaming profile to camelCase

__TESTS__/unit/asset/CloudinaryAsset.test.ts, __TESTS__/unit/url/encoding.test.ts, src/assets/CloudinaryFile.ts, src/assets/CloudinaryImage.ts, src/assets/CloudinaryMedia.ts, src/assets/CloudinaryTransformable.ts, src/index.ts, src/transformation/Transformation.ts
Split CloudinaryAssets into four types (based on the spec)
- File
- Video
- Image
- Media
=> Split CloudinaryAssets into four types

__TESTS__/unit/actions/Resize/CropAction.test.ts, src/values/gravity.ts, src/values/gravity/GravityQualifier.ts, src/values/gravity/xyCenterGravity/XYCenterGravity.ts
=> Add XYCenterGravity

__TESTS__/unit/actions/Border.test.ts, src/actions/border.ts
=> Add round corners to border

DOCS.README.md, __DOC_EXAMPLES__/annotatedExamples/configuration.md, __DOC_EXAMPLES__/annotatedExamples/imageOverlay.md, __DOC_EXAMPLES__/annotatedExamples/resize.md, __DOC_EXAMPLES__/annotatedExamples/rotate.md, __DOC_EXAMPLES__/gettingStarted/helloworld.md, __DOC_EXAMPLES__/gettingStarted/terminology.md, src/index.ts
This PR fixes the documentation examples, some typoes and incorrect imports
This PR also adds missing export types to the index.ts
=> Fix the examples in the docs tutorials and add missing export types

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect.ts
Change vignette to strength instead of level
=> Change vignette to strength instead of level

__TESTS__/unit/actions/Overlay.test.ts, src/actions/underlay.ts, src/values/source.ts, src/values/source/sourceTypes/BaseTextSource.ts, src/values/source/sourceTypes/SubtitlesSource.ts, src/values/source/sourceTypes/TextSource.ts
Allow subtitles not to require text style
- X ] Implementation is aligned to Spec.
=> Allow subtitles not to require text style

.github/pull_request_template.md
This PR template is no longer accurate, we don't need the PHP and private functions hiding.
=> Adjust the PR template

__DOC_RESOURCES__/customStyles.css
Add doc styles provided by the doc team
=> Add required doc styles

__TESTS__/unit/actions/VideoEdit.test.ts, src/actions/videoEdit.ts, src/actions/videoEdit/PreviewAction.ts
Add support for videoEdit.preview()
=> Add support for videoEdit.preview()

__TESTS__/unit/config/cloudinaryConfig.test.ts, src/config/BaseConfig.ts, src/config/URLConfig.ts, src/internal/Action.ts, src/internal/qualifier/Qualifier.ts, src/internal/qualifier/QualifierValue.ts, src/internal/utils/dataStructureUtils.ts
Rename unknown to any in Typescript
=> Rename unknown to any in Typescript

__TESTS__/unit/urlConfig.test.ts
Add missing tests for URL versions
=> Add missing tests for URL versions

__TESTS__/unit/actions/Adjust.test.ts, src/actions/adjust/ReplaceColorAction.ts
Fix incorrect implementation for replaceColor with rgb colors
=> Fix incorrect implementation for replaceColor with rgb colors

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/EffectActions/LeveledEffectAction.ts, src/actions/effect/EffectActions/SimpleEffectAction.ts, src/actions/effect/leveled/deshake.ts, src/values/shakeStrength.ts
Rename deshake.pixels to deshakeStrength, add support for Expression
=> Rename deshake.pixels to deshakeStrength, add support for Expression

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect.ts
=> Add duration to effect

__TESTS__/unit/transformation/transformation.test.ts, src/assets/CloudinaryTransformable.ts, src/transformation/Transformation.ts
change addTransformation() to accept a transformation instance as well as a string
=> change addTransformation() to accept a transformation instance as well as a string

__TESTS__/unit/actions/Delivery.test.ts, src/actions/delivery/DeliveryFormat.ts, src/values/progressive.ts
Add support for ProgressiveMode when using DeliveryFormats
=> Add support for ProgressiveMode when using DeliveryFormats

__TESTS__/unit/actions/Resize/FillAction.test.ts, src/actions/resize.ts, src/actions/resize/ResizeFillAction.ts
Add qualifiers x and y for Resize.fill, to be used with gravity.xyCenter
=> Add qualifiers x and y for Resize.fill, to be used with gravity.xyCenter

__TESTS__/unit/actions/PSDTools.test.ts, src/actions/psdTools/SmartObjectAction.ts
Rename psdTools.byFileName to byLayerName
=> Rename psdTools.byFileName to byLayerName

__TESTS__/unit/actions/PSDTools.test.ts, src/actions/psdTools/GetLayerAction.ts
=> Rename byNumber to byIndex

__TESTS__/unit/actions/Overlay.test.ts, __TESTS__/unit/utils/base64Encode.browser.test.ts, __TESTS__/unit/utils/base64Encode.node.test.ts, src/actions/customFunction/CustomFunctionAction.ts, src/internal/utils/base64Encode.ts
- Remove all padding removal lines.
- Fix tests accordingly
=> Fix the base64 methods to ensure we keep the padding in them

__TESTS__/unit/actions/Overlay.test.ts, __TESTS__/unit/utils/base64Encode.browser.test.ts, __TESTS__/unit/utils/base64Encode.node.test.ts, src/actions/customFunction/CustomFunctionAction.ts, src/assets/CloudinaryImage.ts, src/assets/CloudinaryTransformable.ts, src/internal/utils/base64Encode.ts
Feature/add support for underlay in video
Based on #315
=> Add support for video.underlay (was not previously supported)

src/values/FontAntialias.ts, src/values/audioCodec.ts, src/values/chromaSubSampling.ts, src/values/colorSpace.ts, src/values/dpr.ts, src/values/fontHinting.ts, src/values/fontStyle.ts, src/values/fontWeight.ts, src/values/format.ts, src/values/outlineMode.ts, src/values/progressive.ts, src/values/region.ts, src/values/rotationMode.ts, src/values/shakeStrength.ts, src/values/simulateColorBlind.ts, src/values/textAlignment.ts, src/values/textDecoration.ts, src/values/textStyle.ts, src/values/videoCodecLevel.ts, src/values/videoCodecProfile.ts
=> Remove final @doc annotations

__TESTS__/unit/actions/VideoEdit.test.ts
Add another test case for VideoEdit.trim()
=> Add another test case for VideoEdit.trim()

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect.ts, src/actions/effect/removeBackgroundAction.ts, src/simpleTypes.ts, src/values/video/TimelinePosition.ts
- add support for Effect.removeBackground
- Added a few simple types to easily reuse around the system
- Fixed two incorrect types in TimelinePosition
=> Feature/add support for Effect.removeBackground

src/actions/delivery.ts
No functional change  - Just a rename of a parameter name.
=> Rename the parameter name

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect/leveled/makeTransparent.ts
Rename color to colorToReplace
=> Rename color to colorToReplace

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, src/index.ts
Fix an incorrect test and a missing export from index
=> Fix an incorrect test and a missing export from index

__DOC_RESOURCES__/customStyles.css
…nary/base
Docs - Fix styling in the search component when searching for @cloudinary/base
=> Docs - Fix styling in the search component when searching.

__TESTS__/unit/config/cloudinaryConfig.test.ts, __TESTS__/unit/url/url.test.ts
This pr includes many commented out tests that we should consider whether we want to support the specs they are testing.
=> Add configuration tests

src/config/interfaces/Config/IAccountConfig.ts, src/config/interfaces/Config/IApiConfig.ts, src/config/interfaces/Config/IAuthTokenConfig.ts, src/config/interfaces/Config/ICloudConfig.ts, src/config/interfaces/Config/ICloudinaryAssetConfigurations.ts, src/config/interfaces/Config/ICloudinaryConfigurations.ts, src/config/interfaces/Config/ITagConfig.ts, src/config/interfaces/Config/IURLConfig.ts
- Hide private interfaces that aren't needed yet (they'll be needed for node)
- Add examples to existing members
- Fixed a small type error in the docs
=> Add examples to IURlConfig interfaces

.gitignore, jsdoc.config.json, scripts/buildDocs.js
- Added the SDK version number to the navar and footer.
- Adjusted the package name in the reference
=> Docs - Add version number to the docs reference

__DOC_EXAMPLES__/annotatedExamples/configuration.md, __DOC_EXAMPLES__/annotatedExamples/imageOverlay.md, __DOC_EXAMPLES__/gettingStarted/terminology.md, src/actions/overlay.ts, src/actions/rotate/mode.ts, src/actions/transcode.ts, src/actions/underlay.ts, src/actions/videoEdit/ConcatenateAction.ts, src/qualifiers/background/shared/base/BaseGradientBackground.ts, src/qualifiers/gravity.ts, src/qualifiers/outlineMode.ts, src/qualifiers/progressive.ts, src/transformation/Transformation.ts
Docs - Enhance inline examples in the codebase
- Fix broken examples (or removed them)
- Add complete copy-paste examples existing examples.
=> Docs - Enhance inline examples in the codebase

__TESTS__/unit/actions/Flag.test.ts, src/qualifiers/flag.ts
Add flag for ignore-mask-channels
=> Add flag for ignore-mask-channels

__TESTS__/unit/values/format/Format.test.ts, src/qualifiers/format.ts
=> Add Format.usdz()

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect.ts, src/actions/effect/theme.ts
=> Add Theme Effect

src/actions/border.ts, src/actions/conditional.ts, src/actions/customFunction.ts, src/actions/customFunction/CustomFunctionAction.ts
- Fix some example errors in Border
- Add examples to Custom Function
=> Add examples to custom functions

src/actions/namedTransformation.ts, src/actions/namedTransformation/NamedTransformationAction.ts
Add an example for named transformations
=> Add an example for named transformations

src/actions/resize.ts, src/actions/resize/ResizeAdvancedAction.ts, src/actions/resize/ResizeCropAction.ts, src/actions/resize/ResizeFillAction.ts, src/actions/resize/ResizePadAction.ts, src/actions/resize/ResizeSimpleAction.ts, src/actions/resize/ScaleAction.ts, src/actions/resize/ThumbnailAction.ts, src/qualifiers/gravity.ts
- Add examples to Resize
- Fix styling
=> Add examples to Resize

src/actions/extract.ts, src/assets/CloudinaryTransformable.ts, src/transformation/Transformation.ts
=> Add examples to Extract

src/actions/rotate.ts, src/actions/rotate/RotateAction.ts, src/actions/rotate/byAngle.ts, src/actions/rotate/mode.ts
=> Improve rotate docs

__TESTS_BUNDLE_SIZE__/utils/stringGenerators/importFromDist.ts, src/actions/transcode.ts, src/actions/transcode/AudioCodecAction.ts, src/actions/transcode/AudioFrequencyAction.ts, src/actions/transcode/BitRateAction.ts, src/actions/transcode/FPSAction.ts, src/actions/transcode/FPSRangeAction.ts, src/actions/transcode/KeyframeIntervalsAction.ts, src/actions/transcode/StreamingProfile.ts, src/actions/transcode/ToAnimatedAction.ts, src/actions/transcode/VideoCodecAction.ts, src/config/interfaces/Config/ICloudConfig.ts, src/config/interfaces/Config/ICloudinaryAssetConfigurations.ts
- Improve the docs for transcode
=> Improve the docs for transcode

src/actions/variable.ts, src/actions/variable/SetAction.ts, src/actions/variable/SetAssetReferenceAction.ts, src/actions/variable/SetFromContextAction.ts, src/actions/variable/SetFromMetadataAction.ts, src/actions/variable/VariableAction.ts
=> Improve variable docs

src/actions/rotate.ts, src/actions/roundCorners.ts, src/actions/roundCorners/RoundCornersAction.ts, src/actions/roundCorners/byRadius.ts, src/actions/roundCorners/max.ts
Improve docs for round corners
=> Improve docs for round corners

scripts/build.sh, scripts/buildDocs.js, src/actions/variable.ts
- Add dynamic copy right date
- Add the build:docs to the build script
- Fix a jsdoc synax error
=> Add dynamic copy right date

__TESTS__/backwardsComaptibility/createV1URL.test.ts, src/backwards/transformationProcessing/processRadius.ts
fix v1 url generation to correctly support radius arrays and strings
=> fix v1 url generation to correctly support radius arrays and strings

src/qualifiers/format.ts
updated audio format description
=> updated audio format description

__TESTS__/unit/types/BlendMode.test.ts, src/qualifiers/blendMode.ts
lvl input was added to antiRemoval
=> Add lvl input to antiRemoval

__TESTS__/unit/actions/Animated.test.ts, src/actions.ts, src/actions/animated.ts, src/assets/CloudinaryTransformable.ts, src/transformation/Transformation.ts
=> Added animated action

__DOCS__/examples/annotatedExamples/configuration.md
Reverts cloudinary/cloudinary-js-base#395
=> Revert "remove CloudinaryImage from example"

package.json, scripts/build.sh
1.Added LICENSE and CHANGELOG.md to build
2. Added types node so that we can use `global.Buffer` for node support
=> Added LICENSE and CHANGELOG.md to build

__TESTS__/unit/actions/Resize/CropAction.test.ts, src/actions/resize/ResizeCropAction.ts
=> add zoom support to c_crop

__DOCS__/examples/annotatedExamples/configuration.md
removed image instance example
=> removed image instance example

__TESTS__/unit/url/url.test.ts, src/assets/CloudinaryFile.ts, src/internal/url/cloudinaryURL.ts
remove storage code occurrences and changed into delivery
=> remove storage code occurrences

.code-generation/config.js
This pr defines unsupported transformation params and code, to be used by code generator
=> Add unsupportedTxParams, unsupportedCode to code generation config

__TESTS__/unit/values/gravity/Gravity.test.ts, src/actions/resize/ResizeAdvancedAction.ts
added shortened gravity notation
=> added shortened gravity notation

__TESTS__/backwardsComaptibility/transformationLegacyTests/expression.test.ts, __TESTS__/backwardsComaptibility/transformationLegacyTests/utils/createTestURL.ts, src/actions/adjust.ts, src/actions/adjust/ImproveAction.ts, src/actions/reshape.ts, src/actions/reshape/Shear.ts, src/backwards/createCloudinaryLegacyURL.ts, src/backwards/generateTransformationString.ts, src/backwards/utils/norm_range_values.ts, src/types/types.ts
changed the types directory location
=> changed the types directory location

__TESTS__/unit/actions/Transcode.test.ts, src/actions/transcode.ts, src/types/types.ts
=> shortened AnimatedFormat

__TESTS__/unit/actions/Delivery.test.ts, src/actions/delivery.ts, src/types/types.ts
added shortened format notation
=> added shortened format notation

__TESTS__/unit/actions/Delivery.test.ts, src/actions/delivery.ts, src/types/types.ts
=> added shortened quality notation

__TESTS__/unit/actions/Effect.test.ts, src/actions/effect.ts, src/types/types.ts
added shortened ArtisticFilter notation
=> added shortened ArtisticFilter notation

__TESTS__/unit/actions/Resize/AspectRatio.test.ts, src/actions/resize/ResizeSimpleAction.ts, src/types/types.ts
added shortened notation AspectRatio
=> added shortened notation AspectRatio

.code-generation/config.js
Update config.js for Code Generator
=> Update config.js for code generation

__TESTS__/unit/fromJson/fromJson.test.ts, __TESTS__/unit/toJson/levelEffect.test.ts, __TESTS__/unit/toJson/simpleEffect.test.ts, __TESTS__/unit/toJson/toJson.test.ts, src/actions/effect/EffectActions/LeveledEffectAction.ts, src/actions/effect/EffectActions/SimpleEffectAction.ts, src/internal/internalConstants.ts, src/internal/models/IEffectActionWithLevelModel.ts, src/internal/models/ISimpleEffectActionModel.ts
add tojson to simpleEffect action
1. toJson was added to simpleEffect action
2. toJson was added to sepia()
3. moved from/toJson to respective folders
=> add tojson to simpleEffect action

package.json
removed failing test on node version 12.14
=> removed failing test on node version 12.14

__TESTS__/unit/fromJson/delivery.fromJson.test.ts, src/actions/delivery/DeliveryQualityAction.ts, src/internal/internalConstants.ts
=> fixed fromJson q_auto:best

__TESTS__/unit/fromJson/delivery.fromJson.test.ts, src/internal/internalConstants.ts
Fix fromJson for quality action
=> Fix fromJson for quality action

__TESTS__/unit/fromJson/delivery.fromJson.test.ts, __TESTS__/unit/toJson/delivery.toJson.test.ts, src/actions/delivery.ts, src/actions/delivery/DeliveryAction.ts, src/actions/delivery/DeliveryDPRAction.ts, src/internal/fromJson.ts, src/internal/models/IDeliveryActionModel.ts
update dpr action from/to json
Refactored the internal API so that we can maintain this better
=> update dpr action from/to json

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, __TESTS__/unit/fromJson/adjust.fromJson.test.ts, __TESTS__/unit/fromJson/concatenate.fromJson.test.ts, __TESTS__/unit/fromJson/delivery.fromJson.test.ts, __TESTS__/unit/fromJson/effect.fromJson.test.ts, __TESTS__/unit/fromJson/fromJson.test.ts, __TESTS__/unit/fromJson/resize.fromJson.test.ts, __TESTS__/unit/toJson/adjust.toJson.test.ts, __TESTS__/unit/toJson/concatenate.toJson.test.ts, __TESTS__/unit/toJson/delivery.toJson.test.ts, __TESTS__/unit/toJson/effect.toJson.test.ts, __TESTS__/unit/toJson/resize.toJson.test.ts, src/actions/videoEdit/ConcatenateAction.ts, src/internal/fromJson.ts, src/internal/models/ActionModel.ts, src/internal/models/IFetchSourceModel.ts, src/internal/models/IHasFromJson.ts, src/internal/models/IImageSourceModel.ts, src/internal/models/IQualifierModel.ts, src/internal/models/ITransformationModel.ts, src/internal/models/IVideoSourceModel.ts, src/internal/models/IVideoTransformationModel.ts, src/internal/models/QualifierModel.ts, src/internal/models/actionToJson.ts, src/internal/models/qualifierToJson.ts, src/qualifiers/source/BaseSource.ts, src/qualifiers/source/sourceTypes/FetchSource.ts, src/qualifiers/source/sourceTypes/ImageSource.ts, src/qualifiers/source/sourceTypes/VideoSource.ts, src/transformation/Transformation.ts
* Add ImageSourceModel
* Add FetchSourceModel
* Add TransformationModel
* Fix transformation json representation to be an object instead of an array of actions
* Updated fromJson to accept an updated transformation model {actions: IActionModel[]}
* Update toJson to return an update transformation model
=> Feature/update to/fromJson to return object instead of array & add sources & transformation models

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, __TESTS__/unit/fromJson/effect.fromJson.test.ts, __TESTS__/unit/toJson/effect.toJson.test.ts, src/actions/effect.ts, src/actions/effect/leveled/FadeIn.ts, src/actions/effect/leveled/FadeOut.ts, src/internal/fromJson.ts, src/internal/models/IEffectActionModel.ts
1. refactored fadeIn fadeOut actions to be standalone 
2. add fadeIn fadeOut from/to Json
=> add fadeIn fadeOut from/to Json

__TESTS__/unit/values/gravity/CompassGravity.test.ts, src/qualifiers/gravity.ts, src/qualifiers/gravity/compassGravity/CompassGravity.ts
add string type to compass gravity
=> add string type to compass gravity

__TESTS__/unit/fromJson/effect.fromJson.test.ts, src/actions/effect/leveled/MakeTransparent.ts, src/internal/internalConstants.ts
fix makeTransparent fromJson to return e_make_transparent rather than e_makeTransparent
=> fix makeTransparent

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, __TESTS__/unit/fromJson/transcode.fromJson.test.ts, __TESTS__/unit/toJson/transcode.toJson.test.ts, src/actions/transcode/VideoCodecAction.ts, src/assets/CloudinaryMedia.ts, src/assets/CloudinaryVideo.ts, src/internal/fromJson.ts, src/internal/models/ITranscodeActionModel.ts, src/qualifiers/videoCodec.ts, src/qualifiers/videoCodecType/VideoCodecType.ts
=> Add videoCodec to/fromJson

__TESTS__/unit/fromJson/condition.fromJson.test.ts, __TESTS__/unit/toJson/conditional.toJson.test.ts, src/actions/conditional.ts, src/internal/fromJson.ts, src/internal/models/IConditionalActionModel.ts
Add conditional Action from/toJson
=> Add conditional Action from/toJson

.code-generation/config.js
=> Enable the e_tint syntax

README.md, jsdoc.config.json
Add transformation builder sdk reference docs
=> Add transformation builder sdk reference docs

README.md
Fix the Jest section in Readme
=> Fix jest config section

.code-generation/config.js, .travis.yml, __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, src/backwards/utils/legacyBaseUtil.ts, tsconfig.json, tsconfig.test.json
It will help to implement autogenerated import statements in the SDK code snippets service.
=> Add importStatementsTemplate to langConfig

package.json
Add repository field to `package.json`
=> Add link to github repository

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
increase allowed bundle size by 1 KB
=> increase allowed bundle size by 1 KB

.code-generation/config.js, __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, package.json, yarn.lock
- Remove `roundCorners` from unsupported in config 
- Explicitly bump the `transformation-builder-sdk` dep version
=> Remove roundCorners from unsupported in config

package.json, src/qualifiers/autoFocus.ts, yarn.lock
- Add missing named `onFocus` export in `autoFocus` qualifier
=> Add missing focusOn export

.code-generation/config.js
Add 2 missing methods for code generation
=> add methods for url_suffix and version

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
=> increasing bundle size

src/qualifiers/background.ts
Add missing export for background `generativeFill` qualifier.
=> Add missing Background.generativeFill export

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, __TESTS__/unit/actions/Effect.test.ts, package.json, src/actions/effect.ts, src/actions/effect/GenerativeRecolor.ts
- Added Generative Recolor action
- Added Generative Restore action
=> Add Generative Recolor/Restore actions

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
=> update import size limit test

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, __TESTS__/unit/actions/Effect.test.ts, package.json, src/actions/effect.ts, src/actions/effect/blur/Blur.ts, src/qualifiers/region/CustomRegion.ts
- Add Upscale action
- Update Blur action reexport
=> Add Upscale action

package.json, src/actions/resize.ts
- Re-export `Resize.auto` transformation from `transformation-builder-sdk`
=> Add Resize.auto transformation

package.json
=> Update deps version

package.json, src/qualifiers/source.ts, src/qualifiers/source/sourceTypes/AudioSource.ts
- Support audio as an overlay source
=> Support audio as an overlay source

package.json, src/actions/effect.ts, src/actions/effect/GenerativeBackgroundReplace.ts
- Reexport Generative Background Replace from `transformation-builder-sdk`
=> Add Generative Background Replace action

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
- Increase size limit in test (due to new action)
=> Increase size limit in test

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts, package.json, src/actions/effect.ts, src/actions/effect/Extract.ts
Reexport Extract from transformation-builder-sdk
=> Reexport Extract Transformation
