.babelrc
.eslintrc
__TESTS__/unit/actions/Resize.test.js
jest.config.json
package-lock.json
package.json

- Update jest to allow imports from src without full path (src as root)
- Update eslint to support jest
- Update build script to also lint  __TESTS__
- Install @types/jest for IDE support
- Update babelrc, include test env to allow babel to transform modules for Jest

Update configuration files

---

__TESTS__/unit/scripts/createEntryPoints.test.ts
scripts/lib/entryPointsLib.ts

This PR adds in all our package.json files the "sideEffects:false" key which allows webpack to properly tree shake the ES module files.

Add sideEffects key in package.json for webpack tree shaking

---

__TESTS__/unit/Instance/Cloudinary.test.ts
src/instance/Cloudinary.ts

Notes,
The idea here is to allow users to re-use their configurations without passing them again and again, but also preventing them from accidentally importing all our code at once.
Developers can create an empty Cloudinary instance, and through code `inject` the classes they want to use.
This will allow us in the future to `inject` future plugins without having anything directly in the instance.

Enable usage of an instance with a shared configuration

---

__TESTS__/unit/actions/NamedTransformation.test.ts
src/actions/namedTransformation/INamedTransformationAction.ts
src/actions/namedTransformation/NamedTransformation.ts
src/transformation/TransformableImage.ts

Notes:
Implemented differently from PHP/Kotlin, since we can't have direct operations on the transformation.
Syntax was changed from
`image.namedTransformation('foo')`
to
`image.namedTransformation(name('foo'))`
As always feel free to suggest better names

Add action - Named transformation

---

scripts/updateCompliationTests.js

This PR adds the ability to pass a key to the code generator, allowing the creation of very refined compilation tests
Examples:
* Create a file with all tests containing `a_`
* Create a file with all tests containing `g_`
Example usage:
`KEY=g npm run test:comp`
Additionally, Added general UI improvements to the `updateCompilationsTest.ts` file

Enable passing env variable to code generator

---

__TESTS__/unit/actions/Overlay.text.test.ts
src/actions/layers/ISource.ts
src/actions/layers/Layers.ts
src/actions/layers/Source.ts
src/actions/layers/sources/ImageSource.ts
src/actions/layers/sources/TextSource.ts
src/params/fonts/Fonts.ts

This PR adds support for text overlays.
What was done:
* Created an interface for all sources 
* Method on ISource will now resolve the correct source string (for example `l_sample` vs `l_text:arial_20` 
* Moved the location of the ImageSource to a `/sources` directory under `/Source`
What we should consider moving forward:
* Source should probably be a `Param` (like Position and BlendMode)
* We're still missing docstrings here because it's not clear what we'll end up exporting, Once we have Video Source implemented we'll have the complete picture of what's private and what's public, and we can include the missing docstrings. I've opened internal issues to keep track of these missing docstrings.

Implement text-layer for overlays

---

scripts/updateCompliationTests.js

Fix a broken `npm run build:comp` command when the `compliation.test.ts` file does not exist yet on the file system

Ensure file exists before deleteing - compilations.test.ts

---

__TESTS__/unit/actions/Adjust.test.ts
__TESTS__/unit/actions/Border.test.ts
__TESTS__/unit/actions/Condition.test.ts
__TESTS__/unit/actions/Delivery.test.ts
__TESTS__/unit/actions/Effect.test.ts
__TESTS__/unit/actions/NamedTransformation.test.ts
__TESTS__/unit/actions/Overlay.test.ts
__TESTS__/unit/actions/Quality.test.ts
__TESTS__/unit/actions/Resize.test.ts
__TESTS__/unit/actions/Variable.test.ts
src/transformation/Transformation.ts

This PR reuses the ESM package test we have to reduce code duplication.
Also, fix a minor typing error in a file

Refactor tests to use the ensureESMDefault package

---

.gitignore
__TESTS_BUNDLE_SIZE__/bin/bin.ts
__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
__TESTS_BUNDLE_SIZE__/bundleSizeTestRunner.ts
__TESTS_BUNDLE_SIZE__/interfaces/ITestCase.ts
__TESTS_BUNDLE_SIZE__/utils/consts.ts
__TESTS_BUNDLE_SIZE__/utils/fileSystem/createDistFolder.ts
__TESTS_BUNDLE_SIZE__/utils/fileSystem/createEntryFile.ts
__TESTS_BUNDLE_SIZE__/utils/fileSystem/createTestFolders.ts
__TESTS_BUNDLE_SIZE__/utils/fileSystem/getBundleInfo.ts
__TESTS_BUNDLE_SIZE__/utils/fileSystem/testCleanUp.ts
__TESTS_BUNDLE_SIZE__/utils/log.ts
__TESTS_BUNDLE_SIZE__/utils/stringGenerators/importFromBase.ts
__TESTS_BUNDLE_SIZE__/utils/stringGenerators/importFromDist.ts
__TESTS_BUNDLE_SIZE__/utils/testLifeCycle/handleTestError.ts
__TESTS_BUNDLE_SIZE__/utils/testLifeCycle/handleTestSuccess.ts
__TESTS_BUNDLE_SIZE__/utils/webpack/buildWithWebpack.ts
package.json

This PR adds a test harness that runs test cases which ensure that a combination of import statements doesn't result in unwanted code.
For example, given the following input 
```javascript
import Resize from 'base/resize'
```
We would like to make sure that no extra code is added to the bundle by mistake.
While it's difficult to programmatically test it, we can manually test it once and add a guard to ensure the limits aren't breached.
A test case looks like this
```javascript
{
name: 'Tests a transformable image with Resize',
sizeLimitInKB: 9,
importsArray: [
importFromBase('TransformableImage'), // Utility function to create the `import.... string`
importFromDist('actions/resize') // Utility function to create the `import.... string`
]
}
```
Once we have this test case, we can create a …

Implement the Test Bundle Size harness

---

__TESTS__/unit/actions/Resize.test.ts
src/actions/resize/ResizeAction.ts

Fixes a type issue with whole numebrs passed to aspectRatio
When 1.0 is passed, JS turns it into 1.
so aspectRatio(1.0) turns into ar_1, which is incorrect.
This PR always adds a decimal point

Fix ar_1.0 turning into ar_1

---

package.json

This PR prevents watch mode from building the progress report for the compilation tests (This behaviour is undesired)

Remove unwanted reports from test watchmode

---

src/actions/delivery/dpr.ts
src/constants/dpr/Dpr.ts

Force DPR to always have a decimal point,
This ensures our compilation tests pass as expected, and provides a slightly better developer experience

Force DPR to always have a decimal point

---

__TESTS__/unit/types/Gravity.test.ts
__TESTS__/unit/types/Position.test.ts

Reuses the existing ESM-default tests, this was missed in a previous PR

Reuse existing test functions

---

src/actions/effect/outline.ts

Fix rgb color in outline effect by adding prepareColor(color)

Fix rgb color in outline effect

---

__TESTS__/unit/namespaces/Index.test.ts
src/index.ts

This PR exports the Cloudinary Instance as the default export

Export cloudinary instance as the default

---

__TESTS__/unit/actions/Quality.test.ts
src/actions/delivery/quality.ts
src/values/quality/Quality.ts

Align Quality to Spec (add Quantization, and adjust method names)

Rename auto functions in Quality, add quantization

---

.release-it.json
package.json

This PR fixes an issue where a version release would not bump the version in pacakge.json.
This would happen because the bump script would run on the ./dist/package.json, and not on the package itself.
The fix was done by adding a plugin to release-it (official plugin) that updates multiple files, and not just the default one.

Fix a problem with package.json version after release

---

__TESTS__/unit/scripts/createEntryPoints.test.ts
scripts/lib/entryPointsLib.ts

- Enable require() from node
- Preserve bundle size and tree shaking for bundlers
This PR adds a browser and a main field to the package.json
This was tested manually with multiple bundlers and node

Add support for NodeJS require() syntax

---

__TESTS__/unit/url/encoding.test.ts
src/url/cloudinaryURL.ts
src/utils/serializeCloudinaryCharacters.ts
src/values/sources/sourceTypes/TextSource.ts

This PR provides cloudianry-safe URL encoding,
Please see the various test cases this PR handles (in this PR)
We separate two ways to encode a string:
1. At the action level, this is called Serialization.
2. At the URL level, this is called Encoding.

Add cloudinary-safe url encoding

---

.github/pull_request_template.md
__TESTS__/unit/config/cloudinaryConfig.test.ts
__TESTS__/unit/urlConfig.test.ts
jest.config.json
src/config/CloudinaryConfig.ts
src/config/URLConfig.ts
src/interfaces/Config/IURLConfig.ts
src/internalConstants.ts
src/url/cloudinaryURL.ts

This PR adds support for various URL configurations such as cname, secureDistribution, privateCdn, secure and more.
This PR also removes support for cdbSubDomain as part of 2.0
This PR also has some minor cosmetic spacing changes and fixes some typos

Add support for URL configuration of domains and sub-domains

---

__TESTS_BUNDLE_SIZE__/utils/stringGenerators/importFromDist.ts

The Bundle Size tester attemps to bundle code based on an import path provided by a function.
We recently removed all default exports from the SDK, and left only the named exports.
The import function of the bundle size was importing from `default`, this fix changes it to `import * from` which is no longer the default import.

Fix a bug in the budle size tester that reported incorrect sizes

---

__TESTS__/unit/actions/PSDTools.test.ts
src/actions/psdTools/GetLayerAction.ts
src/actions/psdTools/PsdTools.ts
src/transformation/Transformation.ts
tsconfig.test.json

- Align PSDTools to support multiple qualifiers in a row
- Add src folder for tsconfig.test for better type checking in development

Align PSDTools to support multiple qualifiers in a row

---

__TESTS__/unit/actions/PSDTools.test.ts
src/actions/psdTools/SmartObjectAction.ts

Align smart object to use multiple qualifiers

Align smart object to use multiple qualifiers

---

__TESTS__/unit/actions/Resize/FillPadAction.test.ts
src/actions/resize/ResizeActions/pad/FillPadAction.ts
src/actions/resize/ResizeActions/pad/LimitPadAction.ts
src/actions/resize/ResizeActions/pad/MinimumPadAction.ts
src/actions/resize/ResizeActions/pad/PadAction.ts
src/actions/resize/ResizeActions/shared/ResizePadAction.ts

- Ensure all Resize.pad actions have accurate Gravity types
- Change ResizePad to accept a generic type for Gravity
- Fix resulting bugs in the tests (invalid gravity types used for some resize actions)

Align pad to spec by improving types

---

README.md

Adds a section in the readme about testing this library with Jest.

Add explanations on how to enable babel to test this library

---

src/internal/utils/base64Encode.ts

Remove explicit Buffer calls from the code
Using `Buffer` (without `global.Buffer`) results in typescript injecting Buffer.js into the ode
Buffer.js is a module dedicated to polyfill node's Buffer in the browser, clearly not needed in our project
This PR removes `typeof Buffer` and replaces it with a different check

Remove explicit Buffer calls from the code

---

__TESTS__/unit/actions/Delivery.test.ts
__TESTS__/unit/actions/Effect.test.ts
__TESTS__/unit/actions/Overlay.test.ts
__TESTS__/unit/actions/Pixelate/Pixelate.test.ts
__TESTS__/unit/actions/Resize.test.ts
__TESTS__/unit/actions/RoundCorners.test.ts
__TESTS__/unit/actions/VideoEdit.test.ts
__TESTS__/unit/values/valueImports.test.ts
src/actions/adjust/ReplaceColorAction.ts
src/actions/effect.ts
src/actions/effect/leveled/blackwhite.ts
src/actions/effect/leveled/fadeIn.ts
src/actions/effect/leveled/loop.ts
src/actions/effect/pixelate/pixelate.ts
src/actions/roundCorners/RoundCornersAction.ts
src/actions/videoEdit/TrimAction.ts
src/internal/utils/prepareColor.ts
src/values/colorSpace.ts
src/values/source/sourceTypes/TextSource.ts

Various alignments to the code generator
- Change case (CMYK to cmyk)
- Add safety checks to prepareColor if color is not passed
- Change pixelWidth to squareSize for pixelate
- add tests(and support) for roundCorners radius with value 0
- Add prepareColor to text and subtitle layers' colors
- Add an explicit test for the base64 encoding for remote functions

Various alignments to the code generator

---

__TESTS__/unit/actions/Conditional.test.ts
__TESTS__/unit/transformation/transformation.test.ts
src/actions/videoEdit/ConcatenateAction.ts
src/assets/CloudinaryTransformable.ts
src/transformation/Transformation.ts

Add support for raw action and transformation
- When a string is passed to `addAction()`, validate it does not contain a forward slash
- When a string is passed to `addTransformation()`, perform no validation.

Add support for raw action and transformation

---

__TESTS__/unit/Action/Action.test.ts
__TESTS__/unit/Action/Flag.test.ts
__TESTS__/unit/actions/Flag.test.ts
__TESTS__/unit/actions/Transcode.test.ts
__TESTS__/unit/types/Position.test.ts
__TESTS__/unit/utils/dataStructureUtils/sortMapByKey.test.ts
src/internal/Action.ts
src/internal/qualifier/Qualifier.ts
src/internal/utils/dataStructureUtils.ts

- Add support for addFlag('foo') directly, without a flagQualifier instance
- Remove support for flag concatenation addFlag('foo').addFlag('bar') -> fl_foo,fl_bar (instead of fl_foo.bar)
- Fix tests to match new implementation
Look at the Action instance and how the `addFlag()` method changed, to store the flags in the flags array.
since now we have two places to combine, the mapToSortedArray function also had to change.

Remove flag concatenation

---

__TESTS__/unit/actions/Reshape.test.ts
src/actions/reshape.ts
src/actions/reshape/TrimAction.ts

Implement reshape.trim

---

__TESTS__/unit/actions/Overlay.test.ts
src/values/source/sourceTypes/BaseTextSource.ts

Add a missing prepareColor function call in text background color

Add a missing prepareColor function call in text background color

---

__TESTS__/unit/actions/Resize/LimitFillAction.test.ts
src/actions/resize.ts

Add the X,Y qualifiers to resize.limitFill by returning ResizeFillAction

Add the X,Y qualifiers to resize.limitFill by returning ResizeFillAction

---

__TESTS__/TestUtils/transformations/sampleFacePosition.ts
__TESTS__/unit/actions/Reshape.test.ts
__TESTS__/unit/actions/Resize/ThumbAction.test.ts
__TESTS__/unit/types/Position.test.ts
__TESTS__/unit/values/gravity/AutoGravity.test.ts
__TESTS__/unit/values/gravity/CompassGravity.test.ts
__TESTS__/unit/values/gravity/FocusOnGravity.test.ts
src/values/autoFocus.ts
src/values/compass.ts
src/values/focusOn.ts
src/values/gravity.ts
src/values/gravity/GravityQualifier.ts
src/values/gravity/autoGravity/AutoGravity.ts
src/values/gravity/focusOnGravity/FocusOnGravity.ts

- Move all immediate qualifiers to the root of values
- Fix old import path (@cloudinary/base/values/gravity/qualifiers/focusOn/FocusOn) to be (cloudinary/base/values/focusOn)
- The same was done for AutoFocus and Compass

Flatten the Gravity qualifiers

---

__TESTS__/unit/actions/Adjust.test.ts
src/actions/adjust.ts

Add support for Adjust.tint()

---

README.md

- Remove the readme parts that link to github pages
- In the near future we'll add links to the proper documentation website.

Remove the readme parts that link to github pages

---

__TESTS__/unit/actions/Overlay.test.ts

Add relevant overlay tests from cloudinary-core:
Some of the added tests fail and so we should consider whether they are indeed needed or update the spec/implementation.
Failing tests:
1. 'should serialize a text source'
Not converting spaces to %20
2. 'should serialize a unicode url of fetch source'
Breaking on chinese characters
3. 'should support string interpolation'
This is also failing due to not converting spaces to %20
4. 'should throw an exception if fontFamily is not provided'
TextStyle(null, 17)

Add relevant overlay tests from cloudinary-core

---

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
rollup.config.js
src/index.ts

Breaking - change the name of the named export of the entire SDK
Change from CloudinarySDK to CloudinaryBaseSDK, including the UMD change

Breaking - change the name of the named export of the entire SDK

---

__DOC_RESOURCES__/customStyles.css
src/actions/border.ts

Docs - Add comments and improve some UI areas in the docs

Docs - Add comments and improve some UI areas in the docs

---

__DOC_RESOURCES__/customStyles.css
__docTemplate/src/tmpl/tag/_details.hbs
__docTemplate/template/tmpl.js

Fix indentation in the details tab for any symbol
Before
After

Fix indentation in the details tab for any symbol

---

__TESTS__/unit/asset/CloudinaryFile.test.ts
__TESTS__/unit/config/cloudinaryConfig.test.ts

Add tests for asset.setAssetType function
Remove the function we copied from core and reimplemented it with the right syntax.

Add tests for `asset.setAssetType`

---

__TESTS__/unit/actions/Overlay.test.ts
src/assets/CloudinaryFile.ts
src/internal/utils/base64Encode.ts
src/qualifiers/textStyle.ts

- Add safety to ensure publicID is a string
- Add URL encoding prior to base64 encoding to support unicode URLs (An exception is thrown otherwise)
- Add tests for Text Overlays from v1
-  Adjust test to make sure we don't encode exclamation marks

Add support for unicode characters in l_fetch

---

__TESTS__/unit/actions/CustomFunction.test.ts
__TESTS__/unit/url/encoding.test.ts
src/actions/customFunction/CustomFunctionAction.ts
src/actions/variable/SetAction.ts
src/actions/variable/SetAssetReferenceAction.ts
src/actions/variable/VariableAction.ts
src/internal/utils/base64Encode.ts
src/internal/utils/dataStructureUtils.ts
src/qualifiers/flag/FlagQualifier.ts

Fix issues in previous implementation

Fix issues in previous implementation

---

src/actions/overlay.ts
src/actions/underlay.ts
src/qualifiers/textStyle.ts

Add examples and docstrings to Overlay and Underlay

Add examples and docstrings to Overlay and Underlay

---

src/actions/delivery/DeliveryAction.ts
src/actions/delivery/DeliveryColorSpaceFromICC.ts
src/actions/effect/EffectActions/SimpleEffectAction.ts
src/actions/effect/blur/blur.ts
src/actions/effect/pixelate/pixelate.ts
src/actions/layer/LayerAction.ts
src/actions/namedTransformation/NamedTransformationAction.ts
src/actions/psdTools/ClipAction.ts
src/actions/psdTools/GetLayerAction.ts
src/actions/psdTools/SmartObjectAction.ts
src/actions/reshape.ts
src/actions/reshape/CutByImage.ts
src/actions/reshape/Distort.ts
src/actions/reshape/DistortArc.ts
src/actions/reshape/Shear.ts
src/actions/reshape/TrimAction.ts
src/actions/resize.ts
src/actions/transcode/VideoCodecAction.ts
src/actions/variable/VariableAction.ts
src/sdkAnalytics/getSDKAnalyticsSignature.ts

- Improve the docs for Reshape
- Align several other docs in various files to use the same standard
-

Add better docs to Reshape

---

__DOCS__/JSDocTemplate/src/tmpl/tag/_example.hbs
__DOCS__/JSDocTemplate/template/tmpl.js
src/actions/rotate/RotateAction.ts
src/actions/rotate/mode.ts
src/qualifiers/rotationMode.ts

Fix indentation issues in the code examples in the reference website
Also fix a minor typo in one of the types

Fix indentation issues in the code examples in the reference website

---

__TESTS__/unit/actions/Variable.test.ts
src/actions/variable.ts
src/actions/variable/SetAction.ts

Add new setters to variable: float, integer and string
1. Modify setAction so that the wrapper of a string can be controlled (We needed to control the presence of the ! wrapper)
2. Add three setter methods in Variable
3. Each method performs the required parsing and passes the parsed result into the original SetAction constructor

Add new setters to variable: float, integer and string

---

__TESTS__/backwardsComaptibility/createV1URL.test.ts
src/backwards/generateTransformationString.ts
src/backwards/types.ts
src/backwards/utils/isObject.ts

fix v1 URL generation to correctly support border objects and strings.

fix v1 url generation to correctly support border objects and strings

---

scripts/updateCompliationTests.js

Fix the path of the ruby project from which tests are built

Fix the path of the ruby project from which tests are built

---

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
__TESTS__/backwardsComaptibility/createLegacyURL.test.ts
__TESTS__/backwardsComaptibility/legacyLayerURL.test.ts
jest.config.json
src/backwards/condition.ts
src/backwards/configuration.ts
src/backwards/expression.ts
src/backwards/generateTransformationString.ts
src/backwards/legacyLayer/fetchlayer.ts
src/backwards/legacyLayer/layer.ts
src/backwards/legacyLayer/subtitleslayer.ts
src/backwards/legacyLayer/textlayer.ts
src/backwards/parameters.ts
src/backwards/transformation.ts
src/backwards/transformationProcessing/processDpr.ts
src/backwards/transformationProcessing/processLayer.ts
src/backwards/utils/isEmpty.ts
src/backwards/utils/isFunction.ts
src/backwards/utils/isNumberLike.ts
src/backwards/utils/legacyBaseUtil.ts
src/backwards/utils/snakeCase.ts
src/types/types.ts

1. added backwards compatibility object processing
2. added dpr rounding to float

added backwards compatibility object processing

---

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
package.json
src/assets/CloudinaryMedia.ts
src/backwards/configuration.ts
src/backwards/createCloudinaryLegacyURL.ts
src/backwards/transformation.ts
src/internal/utils/cloneDeep.ts

This pr fixes how lodash.cloneDeep is imported:  
1. import once using import cloneDeep from 'lodash.clonedeep'
2. wrap in a function, so that lodash won't be imported directly incorrectly in other places, and make it so that replacing cloneDeep implementation won't require updating imports.

Fix lodash.cloneDeep import

---

README.md
jsdoc.config.json

- Rename JSDOC Reference website to URL-GEN instead of Base

Rename JSDOC Reference website to URL-GEN instead of Base

---

src/instance/Cloudinary.ts

- Remove un-used property CloudinaryImage from Cloudinary instance
- set the config as a private member
- add a getter for the config.

Add getConfig and remove un-needed property in Cloudinary

---

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
__TESTS__/unit/toJson.test.ts
src/actions/delivery.ts
src/actions/delivery/DeliveryAction.ts
src/actions/delivery/DeliveryColorSpaceFromICC.ts
src/actions/delivery/DeliveryFormat.ts
src/actions/delivery/DeliveryQuality.ts
src/internal/internalConstants.ts
src/internal/models/IDeliveryActionModel.ts
src/qualifiers/flag.ts
src/qualifiers/flag/FlagQualifier.ts
src/qualifiers/format/FormatQualifier.ts
src/qualifiers/progressive.ts

1. Added Delivery.ToJSON
2. updated some types in qualifier flag to fix type errors

added delivery tojson

---

__TESTS__/unit/actions/Resize.test.ts
__TESTS__/unit/fromJson.test.ts
__TESTS__/unit/toJson.test.ts
src/actions/resize/ResizeAdvancedAction.ts
src/actions/resize/ResizePadAction.ts

This adds the option to pass string to pad.gravity like so:
`.addAction(Resize.pad(100).gravity('south');`
Right now, must do this:
`.addAction(Resize.pad(100).gravity(Gravity.compass(Compass.south()))`

Add support for string gravity of pad actions

---

__TESTS__/unit/fromJson/adjust.fromJson.test.ts
src/actions/effect/EffectActions/SimpleEffectAction.ts

fix unsharpMask strength fromJson

fix unsharpMask strength fromJson

---

__TESTS__/unit/index.test.ts
src/config/CloudConfig.ts
src/config/CloudinaryConfig.ts
src/config/URLConfig.ts
src/index.ts

Add CloudConfig and URLConfig to root level exports to remove warnings from Angular 
https://stackoverflow.com/questions/46446080/what-is-a-deep-import-in-angular-4-context

Add CloudConfig exports to root level

---

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
__TESTS__/unit/fromJson/concatenate.fromJson.test.ts
src/actions/videoEdit/ConcatenateAction.ts
src/internal/fromJson.ts
src/internal/models/IConcatenateActionModel.ts
src/internal/models/IHasFromJson.ts
src/internal/models/IQualifierModel.ts
src/internal/models/ISourceModel.ts
src/internal/models/IVideoSourceModel.ts
src/internal/models/IVideoTransformationModel.ts
src/qualifiers/source/sourceTypes/VideoSource.ts

This pr adds fromJson support to Concatenate.
It will be used as base for adding fromJson support to more video.edit actions.
Reviewer please note: I've added a new parameter to the internal fromJson function: tranformationFromJson.
It is used by actions that have internal transformations (like Concatenate) to generate a transformation from json.
Adding the parameter prevents the need to import the function and all it's dependencies inside the Concatenate action or it's source qualifier.

Add ConcatenateAction.fromJson()

---

package.json
scripts/buildDocs.sh
scripts/updateInjectVersionSemver.js

This pr fixes an issue where the build:docs script fails.
jsDoc fails when runned in an execSync but works when manually executed, so I moved it to a bash script, which fixed the issue.

Fix build:docs script by using bash instead of node's execSync

---

rollup.config.js

Change the old BaseSDK library name to CLD_URL_GEN.
I'm very open to naming suggestions.

Change library name for umd bundles

---

package.json

We're getting typescript errors when building the docs. This was related to a change in betterdocs. 
Fixing the version resolves those issues.

fixed betterdocs version in package.json

---

.travis.yml

Our build failed on node 14 due to betterDocs issue, but we did not catch it on travis, so added node 14 to travis.yml

Update travis.yml to run tests on node 12 & node 14

---

__TESTS__/unit/actions/Overlay.test.ts
src/qualifiers/source/sourceTypes/BaseTextSource.ts
src/qualifiers/textFit.ts

Add textFit

---

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
__TESTS__/unit/fromJson/overlayUnderlay.fromJson.test.ts
__TESTS__/unit/toJson/overlayUnderlay.toJson.test.ts
src/actions/layer/LayerAction.ts
src/internal/internalConstants.ts
src/internal/models/IOverlayActionModel.ts

fix antiremoval from to json

---

__TESTS__/unit/testBuild.test.ts
package.json
src/actions/adjust.ts
src/actions/delivery.ts
src/actions/rotate.ts
src/assets/CloudinaryImage.ts
src/qualifiers/FontAntialias.ts
src/qualifiers/animatedFormat.ts
src/qualifiers/artisticFilter.ts
src/qualifiers/aspectRatio.ts
src/qualifiers/audioCodec.ts
src/qualifiers/audioFrequency.ts
src/qualifiers/autoFocus.ts
src/qualifiers/background.ts
src/qualifiers/blendMode.ts
src/qualifiers/chromaSubSampling.ts
src/qualifiers/color.ts
src/qualifiers/compass.ts
src/qualifiers/concatenate.ts
src/qualifiers/gradientDirection/GradientDirectionQualifierValue.ts
src/qualifiers/shakeStrength.ts
src/qualifiers/timeline.ts
src/simpleTypes.ts

This pr addresses https://github.com/cloudinary/js-url-gen/issues/533
1. Removed .js from transformation-builder-sdk imports
2. Added dist test

Fix transformation-builder-sdk imports

---

__TESTS__/unit/url/url.test.ts
__TESTS__/unit/urlConfig.test.ts
src/assets/CloudinaryFile.ts
src/config/URLConfig.ts
src/config/interfaces/Config/IURLConfig.ts
src/internal/internalConstants.ts

Add the ability to provide additional query params to be added to the final generated URL

enable passing query params to URLConfig

---

__TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
package.json
src/actions/effect.ts
src/actions/resize.ts

- Add Enhance and AutoPad actions

Add Enhance and AutoPad actions
